package com.gbanker.core.order.dao.entity;

import java.util.Date;

public class MarginDelivery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.delivery_order_no
     *
     * @mbggenerated
     */
    private String deliveryOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.trade_order_no
     *
     * @mbggenerated
     */
    private String tradeOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.order_type
     *
     * @mbggenerated
     */
    private Byte orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.delivery_weight
     *
     * @mbggenerated
     */
    private Long deliveryWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.order_add_weight
     *
     * @mbggenerated
     */
    private Long orderAddWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.delivery_price
     *
     * @mbggenerated
     */
    private Long deliveryPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.order_add_amount
     *
     * @mbggenerated
     */
    private Long orderAddAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.delivery_add_amount
     *
     * @mbggenerated
     */
    private Long deliveryAddAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.delivery_type
     *
     * @mbggenerated
     */
    private Byte deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.delivery_fee
     *
     * @mbggenerated
     */
    private Long deliveryFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.insrance_fee
     *
     * @mbggenerated
     */
    private Long insranceFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.crate_time
     *
     * @mbggenerated
     */
    private Date crateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_delivery.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.id
     *
     * @return the value of margin_delivery.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.id
     *
     * @param id the value for margin_delivery.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.user_id
     *
     * @return the value of margin_delivery.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.user_id
     *
     * @param userId the value for margin_delivery.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.account_id
     *
     * @return the value of margin_delivery.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.account_id
     *
     * @param accountId the value for margin_delivery.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.delivery_order_no
     *
     * @return the value of margin_delivery.delivery_order_no
     *
     * @mbggenerated
     */
    public String getDeliveryOrderNo() {
        return deliveryOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.delivery_order_no
     *
     * @param deliveryOrderNo the value for margin_delivery.delivery_order_no
     *
     * @mbggenerated
     */
    public void setDeliveryOrderNo(String deliveryOrderNo) {
        this.deliveryOrderNo = deliveryOrderNo == null ? null : deliveryOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.trade_order_no
     *
     * @return the value of margin_delivery.trade_order_no
     *
     * @mbggenerated
     */
    public String getTradeOrderNo() {
        return tradeOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.trade_order_no
     *
     * @param tradeOrderNo the value for margin_delivery.trade_order_no
     *
     * @mbggenerated
     */
    public void setTradeOrderNo(String tradeOrderNo) {
        this.tradeOrderNo = tradeOrderNo == null ? null : tradeOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.order_type
     *
     * @return the value of margin_delivery.order_type
     *
     * @mbggenerated
     */
    public Byte getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.order_type
     *
     * @param orderType the value for margin_delivery.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(Byte orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.delivery_weight
     *
     * @return the value of margin_delivery.delivery_weight
     *
     * @mbggenerated
     */
    public Long getDeliveryWeight() {
        return deliveryWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.delivery_weight
     *
     * @param deliveryWeight the value for margin_delivery.delivery_weight
     *
     * @mbggenerated
     */
    public void setDeliveryWeight(Long deliveryWeight) {
        this.deliveryWeight = deliveryWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.order_add_weight
     *
     * @return the value of margin_delivery.order_add_weight
     *
     * @mbggenerated
     */
    public Long getOrderAddWeight() {
        return orderAddWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.order_add_weight
     *
     * @param orderAddWeight the value for margin_delivery.order_add_weight
     *
     * @mbggenerated
     */
    public void setOrderAddWeight(Long orderAddWeight) {
        this.orderAddWeight = orderAddWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.delivery_price
     *
     * @return the value of margin_delivery.delivery_price
     *
     * @mbggenerated
     */
    public Long getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.delivery_price
     *
     * @param deliveryPrice the value for margin_delivery.delivery_price
     *
     * @mbggenerated
     */
    public void setDeliveryPrice(Long deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.order_add_amount
     *
     * @return the value of margin_delivery.order_add_amount
     *
     * @mbggenerated
     */
    public Long getOrderAddAmount() {
        return orderAddAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.order_add_amount
     *
     * @param orderAddAmount the value for margin_delivery.order_add_amount
     *
     * @mbggenerated
     */
    public void setOrderAddAmount(Long orderAddAmount) {
        this.orderAddAmount = orderAddAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.delivery_add_amount
     *
     * @return the value of margin_delivery.delivery_add_amount
     *
     * @mbggenerated
     */
    public Long getDeliveryAddAmount() {
        return deliveryAddAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.delivery_add_amount
     *
     * @param deliveryAddAmount the value for margin_delivery.delivery_add_amount
     *
     * @mbggenerated
     */
    public void setDeliveryAddAmount(Long deliveryAddAmount) {
        this.deliveryAddAmount = deliveryAddAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.delivery_type
     *
     * @return the value of margin_delivery.delivery_type
     *
     * @mbggenerated
     */
    public Byte getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.delivery_type
     *
     * @param deliveryType the value for margin_delivery.delivery_type
     *
     * @mbggenerated
     */
    public void setDeliveryType(Byte deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.delivery_fee
     *
     * @return the value of margin_delivery.delivery_fee
     *
     * @mbggenerated
     */
    public Long getDeliveryFee() {
        return deliveryFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.delivery_fee
     *
     * @param deliveryFee the value for margin_delivery.delivery_fee
     *
     * @mbggenerated
     */
    public void setDeliveryFee(Long deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.insrance_fee
     *
     * @return the value of margin_delivery.insrance_fee
     *
     * @mbggenerated
     */
    public Long getInsranceFee() {
        return insranceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.insrance_fee
     *
     * @param insranceFee the value for margin_delivery.insrance_fee
     *
     * @mbggenerated
     */
    public void setInsranceFee(Long insranceFee) {
        this.insranceFee = insranceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.crate_time
     *
     * @return the value of margin_delivery.crate_time
     *
     * @mbggenerated
     */
    public Date getCrateTime() {
        return crateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.crate_time
     *
     * @param crateTime the value for margin_delivery.crate_time
     *
     * @mbggenerated
     */
    public void setCrateTime(Date crateTime) {
        this.crateTime = crateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.update_time
     *
     * @return the value of margin_delivery.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.update_time
     *
     * @param updateTime the value for margin_delivery.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_delivery.status
     *
     * @return the value of margin_delivery.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_delivery.status
     *
     * @param status the value for margin_delivery.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}