package com.gbanker.core.order.dao.entity;

import java.util.Date;

public class MarginConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.is_open
     *
     * @mbggenerated
     */
    private Byte isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.close_tip
     *
     * @mbggenerated
     */
    private String closeTip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.max_person_buy
     *
     * @mbggenerated
     */
    private Long maxPersonBuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.max_person_loan
     *
     * @mbggenerated
     */
    private Long maxPersonLoan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.max_hodl_day
     *
     * @mbggenerated
     */
    private Integer maxHodlDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.base_rate
     *
     * @mbggenerated
     */
    private Integer baseRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.discount_rate
     *
     * @mbggenerated
     */
    private Integer discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.effect_time
     *
     * @mbggenerated
     */
    private Date effectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_config.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.id
     *
     * @return the value of margin_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.id
     *
     * @param id the value for margin_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.is_open
     *
     * @return the value of margin_config.is_open
     *
     * @mbggenerated
     */
    public Byte getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.is_open
     *
     * @param isOpen the value for margin_config.is_open
     *
     * @mbggenerated
     */
    public void setIsOpen(Byte isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.close_tip
     *
     * @return the value of margin_config.close_tip
     *
     * @mbggenerated
     */
    public String getCloseTip() {
        return closeTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.close_tip
     *
     * @param closeTip the value for margin_config.close_tip
     *
     * @mbggenerated
     */
    public void setCloseTip(String closeTip) {
        this.closeTip = closeTip == null ? null : closeTip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.max_person_buy
     *
     * @return the value of margin_config.max_person_buy
     *
     * @mbggenerated
     */
    public Long getMaxPersonBuy() {
        return maxPersonBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.max_person_buy
     *
     * @param maxPersonBuy the value for margin_config.max_person_buy
     *
     * @mbggenerated
     */
    public void setMaxPersonBuy(Long maxPersonBuy) {
        this.maxPersonBuy = maxPersonBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.max_person_loan
     *
     * @return the value of margin_config.max_person_loan
     *
     * @mbggenerated
     */
    public Long getMaxPersonLoan() {
        return maxPersonLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.max_person_loan
     *
     * @param maxPersonLoan the value for margin_config.max_person_loan
     *
     * @mbggenerated
     */
    public void setMaxPersonLoan(Long maxPersonLoan) {
        this.maxPersonLoan = maxPersonLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.max_hodl_day
     *
     * @return the value of margin_config.max_hodl_day
     *
     * @mbggenerated
     */
    public Integer getMaxHodlDay() {
        return maxHodlDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.max_hodl_day
     *
     * @param maxHodlDay the value for margin_config.max_hodl_day
     *
     * @mbggenerated
     */
    public void setMaxHodlDay(Integer maxHodlDay) {
        this.maxHodlDay = maxHodlDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.base_rate
     *
     * @return the value of margin_config.base_rate
     *
     * @mbggenerated
     */
    public Integer getBaseRate() {
        return baseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.base_rate
     *
     * @param baseRate the value for margin_config.base_rate
     *
     * @mbggenerated
     */
    public void setBaseRate(Integer baseRate) {
        this.baseRate = baseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.discount_rate
     *
     * @return the value of margin_config.discount_rate
     *
     * @mbggenerated
     */
    public Integer getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.discount_rate
     *
     * @param discountRate the value for margin_config.discount_rate
     *
     * @mbggenerated
     */
    public void setDiscountRate(Integer discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.effect_time
     *
     * @return the value of margin_config.effect_time
     *
     * @mbggenerated
     */
    public Date getEffectTime() {
        return effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.effect_time
     *
     * @param effectTime the value for margin_config.effect_time
     *
     * @mbggenerated
     */
    public void setEffectTime(Date effectTime) {
        this.effectTime = effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.status
     *
     * @return the value of margin_config.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.status
     *
     * @param status the value for margin_config.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.create_time
     *
     * @return the value of margin_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.create_time
     *
     * @param createTime the value for margin_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_config.update_time
     *
     * @return the value of margin_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_config.update_time
     *
     * @param updateTime the value for margin_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}