package com.gbanker.core.order.dao.entity;

import java.util.Date;

public class MarginAddRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.margin_order_no
     *
     * @mbggenerated
     */
    private String marginOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.trade_order_no
     *
     * @mbggenerated
     */
    private String tradeOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.trade_amount
     *
     * @mbggenerated
     */
    private Long tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.before_amount
     *
     * @mbggenerated
     */
    private Long beforeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.after_amount
     *
     * @mbggenerated
     */
    private Long afterAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.crate_time
     *
     * @mbggenerated
     */
    private Date crateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_add_record.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.id
     *
     * @return the value of margin_add_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.id
     *
     * @param id the value for margin_add_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.user_id
     *
     * @return the value of margin_add_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.user_id
     *
     * @param userId the value for margin_add_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.account_id
     *
     * @return the value of margin_add_record.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.account_id
     *
     * @param accountId the value for margin_add_record.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.margin_order_no
     *
     * @return the value of margin_add_record.margin_order_no
     *
     * @mbggenerated
     */
    public String getMarginOrderNo() {
        return marginOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.margin_order_no
     *
     * @param marginOrderNo the value for margin_add_record.margin_order_no
     *
     * @mbggenerated
     */
    public void setMarginOrderNo(String marginOrderNo) {
        this.marginOrderNo = marginOrderNo == null ? null : marginOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.trade_order_no
     *
     * @return the value of margin_add_record.trade_order_no
     *
     * @mbggenerated
     */
    public String getTradeOrderNo() {
        return tradeOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.trade_order_no
     *
     * @param tradeOrderNo the value for margin_add_record.trade_order_no
     *
     * @mbggenerated
     */
    public void setTradeOrderNo(String tradeOrderNo) {
        this.tradeOrderNo = tradeOrderNo == null ? null : tradeOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.trade_amount
     *
     * @return the value of margin_add_record.trade_amount
     *
     * @mbggenerated
     */
    public Long getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.trade_amount
     *
     * @param tradeAmount the value for margin_add_record.trade_amount
     *
     * @mbggenerated
     */
    public void setTradeAmount(Long tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.before_amount
     *
     * @return the value of margin_add_record.before_amount
     *
     * @mbggenerated
     */
    public Long getBeforeAmount() {
        return beforeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.before_amount
     *
     * @param beforeAmount the value for margin_add_record.before_amount
     *
     * @mbggenerated
     */
    public void setBeforeAmount(Long beforeAmount) {
        this.beforeAmount = beforeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.after_amount
     *
     * @return the value of margin_add_record.after_amount
     *
     * @mbggenerated
     */
    public Long getAfterAmount() {
        return afterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.after_amount
     *
     * @param afterAmount the value for margin_add_record.after_amount
     *
     * @mbggenerated
     */
    public void setAfterAmount(Long afterAmount) {
        this.afterAmount = afterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.crate_time
     *
     * @return the value of margin_add_record.crate_time
     *
     * @mbggenerated
     */
    public Date getCrateTime() {
        return crateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.crate_time
     *
     * @param crateTime the value for margin_add_record.crate_time
     *
     * @mbggenerated
     */
    public void setCrateTime(Date crateTime) {
        this.crateTime = crateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_add_record.status
     *
     * @return the value of margin_add_record.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_add_record.status
     *
     * @param status the value for margin_add_record.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}