package com.gbanker.core.activity.dao.entity;

import java.util.Date;

public class AccumulateInvestConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulate_invest_config.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulate_invest_config.act_code
     *
     * @mbggenerated
     */
    private String actCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulate_invest_config.reward_amount
     *
     * @mbggenerated
     */
    private Long rewardAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulate_invest_config.reward_demand_amount
     *
     * @mbggenerated
     */
    private Long rewardDemandAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulate_invest_config.total_store
     *
     * @mbggenerated
     */
    private Integer totalStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulate_invest_config.received_quantity
     *
     * @mbggenerated
     */
    private Integer receivedQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulate_invest_config.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulate_invest_config.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulate_invest_config.id
     *
     * @return the value of accumulate_invest_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulate_invest_config.id
     *
     * @param id the value for accumulate_invest_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulate_invest_config.act_code
     *
     * @return the value of accumulate_invest_config.act_code
     *
     * @mbggenerated
     */
    public String getActCode() {
        return actCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulate_invest_config.act_code
     *
     * @param actCode the value for accumulate_invest_config.act_code
     *
     * @mbggenerated
     */
    public void setActCode(String actCode) {
        this.actCode = actCode == null ? null : actCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulate_invest_config.reward_amount
     *
     * @return the value of accumulate_invest_config.reward_amount
     *
     * @mbggenerated
     */
    public Long getRewardAmount() {
        return rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulate_invest_config.reward_amount
     *
     * @param rewardAmount the value for accumulate_invest_config.reward_amount
     *
     * @mbggenerated
     */
    public void setRewardAmount(Long rewardAmount) {
        this.rewardAmount = rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulate_invest_config.reward_demand_amount
     *
     * @return the value of accumulate_invest_config.reward_demand_amount
     *
     * @mbggenerated
     */
    public Long getRewardDemandAmount() {
        return rewardDemandAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulate_invest_config.reward_demand_amount
     *
     * @param rewardDemandAmount the value for accumulate_invest_config.reward_demand_amount
     *
     * @mbggenerated
     */
    public void setRewardDemandAmount(Long rewardDemandAmount) {
        this.rewardDemandAmount = rewardDemandAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulate_invest_config.total_store
     *
     * @return the value of accumulate_invest_config.total_store
     *
     * @mbggenerated
     */
    public Integer getTotalStore() {
        return totalStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulate_invest_config.total_store
     *
     * @param totalStore the value for accumulate_invest_config.total_store
     *
     * @mbggenerated
     */
    public void setTotalStore(Integer totalStore) {
        this.totalStore = totalStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulate_invest_config.received_quantity
     *
     * @return the value of accumulate_invest_config.received_quantity
     *
     * @mbggenerated
     */
    public Integer getReceivedQuantity() {
        return receivedQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulate_invest_config.received_quantity
     *
     * @param receivedQuantity the value for accumulate_invest_config.received_quantity
     *
     * @mbggenerated
     */
    public void setReceivedQuantity(Integer receivedQuantity) {
        this.receivedQuantity = receivedQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulate_invest_config.create_time
     *
     * @return the value of accumulate_invest_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulate_invest_config.create_time
     *
     * @param createTime the value for accumulate_invest_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulate_invest_config.update_time
     *
     * @return the value of accumulate_invest_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulate_invest_config.update_time
     *
     * @param updateTime the value for accumulate_invest_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}