package com.gbanker.core.activity.dao.entity;

public class UserRegist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.wx_open_id
     *
     * @mbggenerated
     */
    private String wxOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.alipay_open_id
     *
     * @mbggenerated
     */
    private String alipayOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.qq_number
     *
     * @mbggenerated
     */
    private String qqNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.column_1
     *
     * @mbggenerated
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.column_2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_regist.column_3
     *
     * @mbggenerated
     */
    private String column3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.id
     *
     * @return the value of user_regist.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.id
     *
     * @param id the value for user_regist.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.user_id
     *
     * @return the value of user_regist.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.user_id
     *
     * @param userId the value for user_regist.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.user_name
     *
     * @return the value of user_regist.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.user_name
     *
     * @param userName the value for user_regist.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.email
     *
     * @return the value of user_regist.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.email
     *
     * @param email the value for user_regist.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.wx_open_id
     *
     * @return the value of user_regist.wx_open_id
     *
     * @mbggenerated
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.wx_open_id
     *
     * @param wxOpenId the value for user_regist.wx_open_id
     *
     * @mbggenerated
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.alipay_open_id
     *
     * @return the value of user_regist.alipay_open_id
     *
     * @mbggenerated
     */
    public String getAlipayOpenId() {
        return alipayOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.alipay_open_id
     *
     * @param alipayOpenId the value for user_regist.alipay_open_id
     *
     * @mbggenerated
     */
    public void setAlipayOpenId(String alipayOpenId) {
        this.alipayOpenId = alipayOpenId == null ? null : alipayOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.qq_number
     *
     * @return the value of user_regist.qq_number
     *
     * @mbggenerated
     */
    public String getQqNumber() {
        return qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.qq_number
     *
     * @param qqNumber the value for user_regist.qq_number
     *
     * @mbggenerated
     */
    public void setQqNumber(String qqNumber) {
        this.qqNumber = qqNumber == null ? null : qqNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.column_1
     *
     * @return the value of user_regist.column_1
     *
     * @mbggenerated
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.column_1
     *
     * @param column1 the value for user_regist.column_1
     *
     * @mbggenerated
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.column_2
     *
     * @return the value of user_regist.column_2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.column_2
     *
     * @param column2 the value for user_regist.column_2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_regist.column_3
     *
     * @return the value of user_regist.column_3
     *
     * @mbggenerated
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_regist.column_3
     *
     * @param column3 the value for user_regist.column_3
     *
     * @mbggenerated
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }
}