package com.gbanker.core.order.dao.mapper;

import com.gbanker.core.order.dao.entity.MarginInvestBalance;

public interface MarginInvestBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_invest_balance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_invest_balance
     *
     * @mbggenerated
     */
    int insert(MarginInvestBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_invest_balance
     *
     * @mbggenerated
     */
    int insertSelective(MarginInvestBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_invest_balance
     *
     * @mbggenerated
     */
    MarginInvestBalance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_invest_balance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarginInvestBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_invest_balance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarginInvestBalance record);
}