package com.gbanker.core.order.dao.mapper;

import com.gbanker.core.order.dao.entity.MarginAddRecord;

public interface MarginAddRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_add_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_add_record
     *
     * @mbggenerated
     */
    int insert(MarginAddRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_add_record
     *
     * @mbggenerated
     */
    int insertSelective(MarginAddRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_add_record
     *
     * @mbggenerated
     */
    MarginAddRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_add_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarginAddRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_add_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarginAddRecord record);
}