package com.gbanker.core.order.dao.mapper;

import com.gbanker.core.order.dao.entity.MarginConfig;

public interface MarginConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_config
     *
     * @mbggenerated
     */
    int insert(MarginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_config
     *
     * @mbggenerated
     */
    int insertSelective(MarginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_config
     *
     * @mbggenerated
     */
    MarginConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarginConfig record);
}