package com.gbanker.core.order.dao.mapper;

import com.gbanker.core.order.dao.entity.MarginDelivery;

public interface MarginDeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_delivery
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_delivery
     *
     * @mbggenerated
     */
    int insert(MarginDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_delivery
     *
     * @mbggenerated
     */
    int insertSelective(MarginDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_delivery
     *
     * @mbggenerated
     */
    MarginDelivery selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_delivery
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarginDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_delivery
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarginDelivery record);
}