package com.gbanker.core.order.dao.mapper;

import com.gbanker.core.order.dao.entity.RechargePay;

public interface RechargePayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_pay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_pay
     *
     * @mbggenerated
     */
    int insert(RechargePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_pay
     *
     * @mbggenerated
     */
    int insertSelective(RechargePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_pay
     *
     * @mbggenerated
     */
    RechargePay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RechargePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RechargePay record);
}