package com.gbanker.service.mtrade.dao.entity;

import java.util.Date;

public class SettleDailyBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.merchant_name
     *
     * @mbggenerated
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.merchant_code
     *
     * @mbggenerated
     */
    private String merchantCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.merchant_account
     *
     * @mbggenerated
     */
    private String merchantAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.settle_no
     *
     * @mbggenerated
     */
    private String settleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.settle_date
     *
     * @mbggenerated
     */
    private Date settleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.balance_trade_amount
     *
     * @mbggenerated
     */
    private Long balanceTradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.bank_trade_amount
     *
     * @mbggenerated
     */
    private Long bankTradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.bank_serial_no
     *
     * @mbggenerated
     */
    private String bankSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.fix_buy_money
     *
     * @mbggenerated
     */
    private Long fixBuyMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.fix_sale_money
     *
     * @mbggenerated
     */
    private Long fixSaleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.fix_buy_bank_money
     *
     * @mbggenerated
     */
    private Long fixBuyBankMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.fix_sale_bank_money
     *
     * @mbggenerated
     */
    private Long fixSaleBankMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.fix_sale_fee
     *
     * @mbggenerated
     */
    private Long fixSaleFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.fix_interest
     *
     * @mbggenerated
     */
    private Long fixInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.account_request_no
     *
     * @mbggenerated
     */
    private String accountRequestNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_daily_bill.bank_serial_voucher
     *
     * @mbggenerated
     */
    private String bankSerialVoucher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.id
     *
     * @return the value of settle_daily_bill.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.id
     *
     * @param id the value for settle_daily_bill.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.merchant_name
     *
     * @return the value of settle_daily_bill.merchant_name
     *
     * @mbggenerated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.merchant_name
     *
     * @param merchantName the value for settle_daily_bill.merchant_name
     *
     * @mbggenerated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.merchant_code
     *
     * @return the value of settle_daily_bill.merchant_code
     *
     * @mbggenerated
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.merchant_code
     *
     * @param merchantCode the value for settle_daily_bill.merchant_code
     *
     * @mbggenerated
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.merchant_account
     *
     * @return the value of settle_daily_bill.merchant_account
     *
     * @mbggenerated
     */
    public String getMerchantAccount() {
        return merchantAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.merchant_account
     *
     * @param merchantAccount the value for settle_daily_bill.merchant_account
     *
     * @mbggenerated
     */
    public void setMerchantAccount(String merchantAccount) {
        this.merchantAccount = merchantAccount == null ? null : merchantAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.settle_no
     *
     * @return the value of settle_daily_bill.settle_no
     *
     * @mbggenerated
     */
    public String getSettleNo() {
        return settleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.settle_no
     *
     * @param settleNo the value for settle_daily_bill.settle_no
     *
     * @mbggenerated
     */
    public void setSettleNo(String settleNo) {
        this.settleNo = settleNo == null ? null : settleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.settle_date
     *
     * @return the value of settle_daily_bill.settle_date
     *
     * @mbggenerated
     */
    public Date getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.settle_date
     *
     * @param settleDate the value for settle_daily_bill.settle_date
     *
     * @mbggenerated
     */
    public void setSettleDate(Date settleDate) {
        this.settleDate = settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.balance_trade_amount
     *
     * @return the value of settle_daily_bill.balance_trade_amount
     *
     * @mbggenerated
     */
    public Long getBalanceTradeAmount() {
        return balanceTradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.balance_trade_amount
     *
     * @param balanceTradeAmount the value for settle_daily_bill.balance_trade_amount
     *
     * @mbggenerated
     */
    public void setBalanceTradeAmount(Long balanceTradeAmount) {
        this.balanceTradeAmount = balanceTradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.bank_trade_amount
     *
     * @return the value of settle_daily_bill.bank_trade_amount
     *
     * @mbggenerated
     */
    public Long getBankTradeAmount() {
        return bankTradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.bank_trade_amount
     *
     * @param bankTradeAmount the value for settle_daily_bill.bank_trade_amount
     *
     * @mbggenerated
     */
    public void setBankTradeAmount(Long bankTradeAmount) {
        this.bankTradeAmount = bankTradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.bank_serial_no
     *
     * @return the value of settle_daily_bill.bank_serial_no
     *
     * @mbggenerated
     */
    public String getBankSerialNo() {
        return bankSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.bank_serial_no
     *
     * @param bankSerialNo the value for settle_daily_bill.bank_serial_no
     *
     * @mbggenerated
     */
    public void setBankSerialNo(String bankSerialNo) {
        this.bankSerialNo = bankSerialNo == null ? null : bankSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.fix_buy_money
     *
     * @return the value of settle_daily_bill.fix_buy_money
     *
     * @mbggenerated
     */
    public Long getFixBuyMoney() {
        return fixBuyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.fix_buy_money
     *
     * @param fixBuyMoney the value for settle_daily_bill.fix_buy_money
     *
     * @mbggenerated
     */
    public void setFixBuyMoney(Long fixBuyMoney) {
        this.fixBuyMoney = fixBuyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.fix_sale_money
     *
     * @return the value of settle_daily_bill.fix_sale_money
     *
     * @mbggenerated
     */
    public Long getFixSaleMoney() {
        return fixSaleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.fix_sale_money
     *
     * @param fixSaleMoney the value for settle_daily_bill.fix_sale_money
     *
     * @mbggenerated
     */
    public void setFixSaleMoney(Long fixSaleMoney) {
        this.fixSaleMoney = fixSaleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.fix_buy_bank_money
     *
     * @return the value of settle_daily_bill.fix_buy_bank_money
     *
     * @mbggenerated
     */
    public Long getFixBuyBankMoney() {
        return fixBuyBankMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.fix_buy_bank_money
     *
     * @param fixBuyBankMoney the value for settle_daily_bill.fix_buy_bank_money
     *
     * @mbggenerated
     */
    public void setFixBuyBankMoney(Long fixBuyBankMoney) {
        this.fixBuyBankMoney = fixBuyBankMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.fix_sale_bank_money
     *
     * @return the value of settle_daily_bill.fix_sale_bank_money
     *
     * @mbggenerated
     */
    public Long getFixSaleBankMoney() {
        return fixSaleBankMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.fix_sale_bank_money
     *
     * @param fixSaleBankMoney the value for settle_daily_bill.fix_sale_bank_money
     *
     * @mbggenerated
     */
    public void setFixSaleBankMoney(Long fixSaleBankMoney) {
        this.fixSaleBankMoney = fixSaleBankMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.fix_sale_fee
     *
     * @return the value of settle_daily_bill.fix_sale_fee
     *
     * @mbggenerated
     */
    public Long getFixSaleFee() {
        return fixSaleFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.fix_sale_fee
     *
     * @param fixSaleFee the value for settle_daily_bill.fix_sale_fee
     *
     * @mbggenerated
     */
    public void setFixSaleFee(Long fixSaleFee) {
        this.fixSaleFee = fixSaleFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.fix_interest
     *
     * @return the value of settle_daily_bill.fix_interest
     *
     * @mbggenerated
     */
    public Long getFixInterest() {
        return fixInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.fix_interest
     *
     * @param fixInterest the value for settle_daily_bill.fix_interest
     *
     * @mbggenerated
     */
    public void setFixInterest(Long fixInterest) {
        this.fixInterest = fixInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.account_request_no
     *
     * @return the value of settle_daily_bill.account_request_no
     *
     * @mbggenerated
     */
    public String getAccountRequestNo() {
        return accountRequestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.account_request_no
     *
     * @param accountRequestNo the value for settle_daily_bill.account_request_no
     *
     * @mbggenerated
     */
    public void setAccountRequestNo(String accountRequestNo) {
        this.accountRequestNo = accountRequestNo == null ? null : accountRequestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.create_time
     *
     * @return the value of settle_daily_bill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.create_time
     *
     * @param createTime the value for settle_daily_bill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.update_time
     *
     * @return the value of settle_daily_bill.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.update_time
     *
     * @param updateTime the value for settle_daily_bill.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.status
     *
     * @return the value of settle_daily_bill.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.status
     *
     * @param status the value for settle_daily_bill.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.description
     *
     * @return the value of settle_daily_bill.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.description
     *
     * @param description the value for settle_daily_bill.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_daily_bill.bank_serial_voucher
     *
     * @return the value of settle_daily_bill.bank_serial_voucher
     *
     * @mbggenerated
     */
    public String getBankSerialVoucher() {
        return bankSerialVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_daily_bill.bank_serial_voucher
     *
     * @param bankSerialVoucher the value for settle_daily_bill.bank_serial_voucher
     *
     * @mbggenerated
     */
    public void setBankSerialVoucher(String bankSerialVoucher) {
        this.bankSerialVoucher = bankSerialVoucher == null ? null : bankSerialVoucher.trim();
    }
}