package com.gbanker.core.activity.dao.mapper;

import com.gbanker.core.activity.dao.entity.AccumulateInvestConfig;

public interface AccumulateInvestConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulate_invest_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulate_invest_config
     *
     * @mbggenerated
     */
    int insert(AccumulateInvestConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulate_invest_config
     *
     * @mbggenerated
     */
    int insertSelective(AccumulateInvestConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulate_invest_config
     *
     * @mbggenerated
     */
    AccumulateInvestConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulate_invest_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccumulateInvestConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulate_invest_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccumulateInvestConfig record);
}