package com.gbanker.core.activity.dao.mapper;

import java.util.Date;

public class UserPassword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.password_type
     *
     * @mbggenerated
     */
    private Integer passwordType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.last_error_login_time
     *
     * @mbggenerated
     */
    private Date lastErrorLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.error_login_count
     *
     * @mbggenerated
     */
    private Integer errorLoginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.password_type
     *
     * @return the value of user_password.password_type
     *
     * @mbggenerated
     */
    public Integer getPasswordType() {
        return passwordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.password_type
     *
     * @param passwordType the value for user_password.password_type
     *
     * @mbggenerated
     */
    public void setPasswordType(Integer passwordType) {
        this.passwordType = passwordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.password
     *
     * @return the value of user_password.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.password
     *
     * @param password the value for user_password.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.last_error_login_time
     *
     * @return the value of user_password.last_error_login_time
     *
     * @mbggenerated
     */
    public Date getLastErrorLoginTime() {
        return lastErrorLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.last_error_login_time
     *
     * @param lastErrorLoginTime the value for user_password.last_error_login_time
     *
     * @mbggenerated
     */
    public void setLastErrorLoginTime(Date lastErrorLoginTime) {
        this.lastErrorLoginTime = lastErrorLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.error_login_count
     *
     * @return the value of user_password.error_login_count
     *
     * @mbggenerated
     */
    public Integer getErrorLoginCount() {
        return errorLoginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.error_login_count
     *
     * @param errorLoginCount the value for user_password.error_login_count
     *
     * @mbggenerated
     */
    public void setErrorLoginCount(Integer errorLoginCount) {
        this.errorLoginCount = errorLoginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.status
     *
     * @return the value of user_password.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.status
     *
     * @param status the value for user_password.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}