package com.gbanker.core.activity.dao.mapper;

import com.gbanker.core.activity.dao.entity.UserRegist;

public interface UserRegistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_regist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_regist
     *
     * @mbggenerated
     */
    int insert(UserRegist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_regist
     *
     * @mbggenerated
     */
    int insertSelective(UserRegist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_regist
     *
     * @mbggenerated
     */
    UserRegist selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_regist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRegist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_regist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRegist record);
}