package com.gbanker.service.mtrade.dao.mapper;

import com.gbanker.service.mtrade.dao.entity.SettleDailyBill;

import java.util.Date;

public interface SettleDailyBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_daily_bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_daily_bill
     *
     * @mbggenerated
     */
    int insert(SettleDailyBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_daily_bill
     *
     * @mbggenerated
     */
    int insertSelective(SettleDailyBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_daily_bill
     *
     * @mbggenerated
     */
    SettleDailyBill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_daily_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SettleDailyBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_daily_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SettleDailyBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_daily_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SettleDailyBill record);

    SettleDailyBill selectByMerchantAndDate(@Param("merchantCode")String merchantCode,@Param("settleDate")Date settleDate);
}