package com.gbanker.face.dao.entity;

import java.util.Date;

public class UserRealInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.id_number
     *
     * @mbggenerated
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.id_number_img
     *
     * @mbggenerated
     */
    private String idNumberImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.img_verify_number
     *
     * @mbggenerated
     */
    private Integer imgVerifyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.img_status
     *
     * @mbggenerated
     */
    private Integer imgStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.certificate_authority
     *
     * @mbggenerated
     */
    private Integer certificateAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.certification_remind
     *
     * @mbggenerated
     */
    private Integer certificationRemind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.first_invest_time
     *
     * @mbggenerated
     */
    private Date firstInvestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_real_info.real_name_time
     *
     * @mbggenerated
     */
    private Date realNameTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.id
     *
     * @return the value of user_real_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.id
     *
     * @param id the value for user_real_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.user_id
     *
     * @return the value of user_real_info.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.user_id
     *
     * @param userId the value for user_real_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.real_name
     *
     * @return the value of user_real_info.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.real_name
     *
     * @param realName the value for user_real_info.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.id_number
     *
     * @return the value of user_real_info.id_number
     *
     * @mbggenerated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.id_number
     *
     * @param idNumber the value for user_real_info.id_number
     *
     * @mbggenerated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.id_number_img
     *
     * @return the value of user_real_info.id_number_img
     *
     * @mbggenerated
     */
    public String getIdNumberImg() {
        return idNumberImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.id_number_img
     *
     * @param idNumberImg the value for user_real_info.id_number_img
     *
     * @mbggenerated
     */
    public void setIdNumberImg(String idNumberImg) {
        this.idNumberImg = idNumberImg == null ? null : idNumberImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.img_verify_number
     *
     * @return the value of user_real_info.img_verify_number
     *
     * @mbggenerated
     */
    public Integer getImgVerifyNumber() {
        return imgVerifyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.img_verify_number
     *
     * @param imgVerifyNumber the value for user_real_info.img_verify_number
     *
     * @mbggenerated
     */
    public void setImgVerifyNumber(Integer imgVerifyNumber) {
        this.imgVerifyNumber = imgVerifyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.img_status
     *
     * @return the value of user_real_info.img_status
     *
     * @mbggenerated
     */
    public Integer getImgStatus() {
        return imgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.img_status
     *
     * @param imgStatus the value for user_real_info.img_status
     *
     * @mbggenerated
     */
    public void setImgStatus(Integer imgStatus) {
        this.imgStatus = imgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.customer_id
     *
     * @return the value of user_real_info.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.customer_id
     *
     * @param customerId the value for user_real_info.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.certificate_authority
     *
     * @return the value of user_real_info.certificate_authority
     *
     * @mbggenerated
     */
    public Integer getCertificateAuthority() {
        return certificateAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.certificate_authority
     *
     * @param certificateAuthority the value for user_real_info.certificate_authority
     *
     * @mbggenerated
     */
    public void setCertificateAuthority(Integer certificateAuthority) {
        this.certificateAuthority = certificateAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.certification_remind
     *
     * @return the value of user_real_info.certification_remind
     *
     * @mbggenerated
     */
    public Integer getCertificationRemind() {
        return certificationRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.certification_remind
     *
     * @param certificationRemind the value for user_real_info.certification_remind
     *
     * @mbggenerated
     */
    public void setCertificationRemind(Integer certificationRemind) {
        this.certificationRemind = certificationRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.first_invest_time
     *
     * @return the value of user_real_info.first_invest_time
     *
     * @mbggenerated
     */
    public Date getFirstInvestTime() {
        return firstInvestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.first_invest_time
     *
     * @param firstInvestTime the value for user_real_info.first_invest_time
     *
     * @mbggenerated
     */
    public void setFirstInvestTime(Date firstInvestTime) {
        this.firstInvestTime = firstInvestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.order_no
     *
     * @return the value of user_real_info.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.order_no
     *
     * @param orderNo the value for user_real_info.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_real_info.real_name_time
     *
     * @return the value of user_real_info.real_name_time
     *
     * @mbggenerated
     */
    public Date getRealNameTime() {
        return realNameTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_real_info.real_name_time
     *
     * @param realNameTime the value for user_real_info.real_name_time
     *
     * @mbggenerated
     */
    public void setRealNameTime(Date realNameTime) {
        this.realNameTime = realNameTime;
    }
}