package com.gbanker.face.dao.mapper;

import com.gbanker.face.dao.entity.UserRealInfo;

public interface UserRealInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_info
     *
     * @mbggenerated
     */
    int insert(UserRealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_info
     *
     * @mbggenerated
     */
    int insertSelective(UserRealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_info
     *
     * @mbggenerated
     */
    UserRealInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRealInfo record);
}