package com.gbanker.gataway.repository;

import com.gbanker.gataway.entity.UserDeviceActive;

public interface UserDeviceActiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_active
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_active
     *
     * @mbggenerated
     */
    int insert(UserDeviceActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_active
     *
     * @mbggenerated
     */
    int insertSelective(UserDeviceActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_active
     *
     * @mbggenerated
     */
    UserDeviceActive selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_active
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDeviceActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_active
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDeviceActive record);
}